version: "2"
run:
  go: "1.22"
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomodguard
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    dupl:
      threshold: 200
    gocyclo:
      min-complexity: 20
    gomodguard:
      allowed:
        modules:
          - github.com/nextmv-io/sdk
          - github.com/nextmv-io/sdk/measure/here
          - github.com/nextmv-io/sdk/measure/osrm
          - github.com/nextmv-io/sdk/measure/google
          - github.com/nextmv-io/sdk/measure/routingkit
          - googlemaps.github.io/maps
          - github.com/dgraph-io/ristretto
          - go.uber.org/mock
          - github.com/google/go-cmp
          - github.com/hashicorp/golang-lru
          - github.com/nextmv-io/go-routingkit
          - github.com/twpayne/go-polyline
          - googlemaps.github.io/maps
          - github.com/itzg/go-flagsfiller
          - github.com/gorilla/schema
          - github.com/google/uuid
          - github.com/xeipuuv/gojsonschema
          - github.com/danielgtaylor/huma
          - github.com/sergi/go-diff
    lll:
      line-length: 120
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - tagliatelle
        path: measure/load\.go
        text: measure
      - linters:
          - gosec
        path: measure/osrm/matrix_test\.go
        text: G404
      - linters:
          - gocritic
        path: run/run\.go
        text: newDeref
      - linters:
          - lll
        path: run/http_runner_config\.go
      - linters:
          - gocyclo
          - gosec
          - nestif
        path: golden/.+\.go
      - linters:
          - gosec
        path: run/tests/http/async/main\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
