name: go test
on: [push]
jobs:
  sdk-go-build-test:
    runs-on: ubuntu-latest
    # Use a matrix strategy to test all the modules simultaneously.
    strategy:
      fail-fast: false
      matrix:
        MOD_PATH:
          [
            ./,
            ./measure/google,
            ./measure/here,
            ./measure/osrm,
            ./measure/routingkit,
          ]
    steps:
      # Checks out the changes.
      - name: git clone
        uses: actions/checkout@v4

      # Determines the Go version to use.
      - name: determine Go version
        run: |
          export GO_VERSION=$(cat workflow-configuration.yml | yq '.go-version' -r)
          echo "Using Go version $GO_VERSION"
          echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV

      # Sets up Go with the version set before.
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      # Builds the Go code.
      - name: go build
        run: go build -v ./...
        working-directory: ${{ matrix.MOD_PATH }}

      # Runs the Go tests.
      - name: go test
        run: go test ./...
        working-directory: ${{ matrix.MOD_PATH }}
