name: markdown lint
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  sdk-markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: DavidAnson/markdownlint-cli2-action@v7
        with:
          globs: "**/*.md"
